version: "3.8"
services:
  postgresDB:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminpg
      POSTGRES_DB: mini_netflix
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5435:5432"
